#this code will be executed and, in case there is a ValueError, this means that the value entered is not a value with an integer form
#the code will raise an error and the exception handling will catch the error

while True:
  try:
    number = int(input("Enter a number: "))
    break
  except ValueError:
    print("This is not a valid number. Try again")
